registered;Registered;http://hl7.org/fhir/observation-status
preliminary;Preliminary;http://hl7.org/fhir/observation-status
final;Final;http://hl7.org/fhir/observation-status
amended;Amended;http://hl7.org/fhir/observation-status
corrected;Corrected;http://hl7.org/fhir/observation-status
cancelled;Cancelled;http://hl7.org/fhir/observation-status
entered-in-error;Entered in Error;http://hl7.org/fhir/observation-status
unknown;Unknown;http://hl7.org/fhir/observation-status