22602-7;Varicella zoster virus IgG Ab [Titer] in Serum;http://loinc.org
22502-9;Measles virus IgG Ab [Titer] in Serum;http://loinc.org
41763-4;Rubella virus IgG Ab [Titer] in Serum;http://loinc.org
22313-1;Hepatitis A virus IgG Ab [Units/volume] in Serum;http://loinc.org
16935-9;Hepatitis B virus surface Ab [Units/volume] in Serum;http://loinc.org
26061-2;European tick borne encephalitis virus Ab [Titer] in Serum;http://loinc.org
6589-6;Yellow fever virus Ab [Titer] in Serum by Immunofluorescence;http://loinc.org
58770-9;Clostridium tetani toxoid IgG Ab [Units/volume] in Serum by Immunofluorescence;http://loinc.org
94505-5;SARS-CoV-2 (COVID-19) IgG Ab [Units/volume] in Serum or Plasma by Immunoassay;http://loinc.org
14128-3;Rabies virus Ab [Titer] in Serum;http://loinc.org
22755-3;Haemophilus influenzae B Ab [Mass/volume] in Serum;http://loinc.org
25531-5;Streptococcus pneumoniae Ab [Mass/volume] in Serum;http://loinc.org