@startuml
skinparam linetype ortho
left to right direction

node IDP

component Impfmodule as "vaccination-module-backend" {
  
  portin port_utility     as "/utility"
  portin port_saml        as "/saml"
  portin port_signature   as "/signature/validate"
  portin port_medicalProblem as "/medicalProblem"
  portin port_allergy     as "/allergy"
  portin port_pastillness as "/pastillness"
  portin port_vaccination as "/vaccination"
  portin port_vacRecord   as "/vaccinationRecord"

  component BaseController
  component VaccinationController
  component PastIllnessController
  component AllergyController
  component MedicalProblemController
  component VaccinationRecordController
  component PortalController
  component UtilityController
  component SamlController

  component VaccinationService
  component PastIllnessService
  component AllergyService
  component MedicalProblemService
  component BaseService
  component VaccinationRecordService
  component PdfService
  component ValueListService
  component SignatureService
  component SamlService {
    portout idp
  } 

  component HuskyAdapter {
     portout PDQ
     portout ATNA
     portout Internal_RSQ
     portout External_RSQ
     portout Internal_RDS
     portout External_RDS
     portout SubmitDoc
     portout XUA
  }
  component Cache
  component FhirAdapter
}

BaseController        --> BaseService
BaseService           -u-> FhirAdapter
BaseService           --> HuskyAdapter

port_vaccination      --> VaccinationController
VaccinationController ..> BaseController
VaccinationController --> VaccinationService
VaccinationService    ..> BaseService

port_pastillness      --> PastIllnessController
PastIllnessController ..> BaseController
PastIllnessController --> PastIllnessService
PastIllnessService    ..> BaseService

port_allergy          --> AllergyController
AllergyController     ..> BaseController
AllergyController     --> AllergyService
AllergyService        ..> BaseService

port_medicalProblem   --> MedicalProblemController
MedicalProblemController ..> BaseController
MedicalProblemController --> MedicalProblemService
MedicalProblemService    ..> BaseService

port_vacRecord        --> VaccinationRecordController
VaccinationRecordController --> VaccinationRecordService
VaccinationRecordController --> PdfService
VaccinationRecordService -d-> FhirAdapter
VaccinationRecordService --> HuskyAdapter

BaseService           --> Cache
HuskyAdapter         -d-> Cache

port_signature        --> PortalController
PortalController      --> SignatureService

port_saml             --> SamlController
SamlController        --> SamlService

port_utility          --> UtilityController
UtilityController     --> ValueListService

node EPD
node GAZELLE
node EPDPLAYGROUND
node POST

PDQ           --> GAZELLE
XUA           --> GAZELLE
Internal_RSQ  --> GAZELLE
External_RSQ  --> GAZELLE
Internal_RDS  --> GAZELLE
External_RDS  --> GAZELLE
SubmitDoc     --> GAZELLE
ATNA          --> GAZELLE
idp           --> IDP

GAZELLE       <.. EPD : instanciate
EPDPLAYGROUND <.. EPD : instanciate
POST          <.. EPD : instanciate

legend left
  -- /vaccination --
  GET // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId} //
  POST // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId} RequestBody VaccinationDTO //
  POST // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody VaccinationDTO //
  POST // /validate/communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody VaccinationDTO //
  DELETE // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody ValueDTO (confidentiality) //
  -- /allergy--
  GET // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId} //
  POST // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId} RequestBody AllergyDTO //
  POST // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody AllergyDTO //
  POST // /validate/communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody AllergyDTO //
  DELETE // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody ValueDTO (confidentiality) //
  -- /pastillness--
  GET // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId} //
  POST // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId} RequestBody PastIllnessDTO //
  POST // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody PastIllnessDTO //
  POST // /validate/communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody PastIllnessDTO //
  DELETE // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody ValueDTO (confidentiality) //
  -- /medicalProblem--
  GET // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId} //
  POST // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId} RequestBody MedicalProblemDTO //
  POST // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody MedicalProblemDTO //
  POST // /validate/communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody MedicalProblemDTO //
  DELETE // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId}/uuid/{uuid} RequestBody ValueDTO (confidentiality) //
  -- /vaccinationRecord --
  GET // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId} //
  POST // /communityIdentifier/{communityIdentifier}/oid/{oid}/localId/{localId} RequestBody VaccinationRecordDTO //
  POST // /exportToPDF RequestBody VaccinationRecordDTO //
  -- /signature --
  POST // /validate RequestBody queryString //
  -- /saml  --
  POST // /logout RequestBody samlXML //
  GET // /login/{idpIdentifier} //
  GET // /sso?SAMLart={samlArtifact} //

  -- /utility--
  GET // /getAllValuesLists //
  GET // /vaccinesToTargetDiseases //
  GET // /setLocalMode/{active} //

end legend

@enduml