@startuml

artifact SpringbootParent [
  spring-boot-starter-parent
  2.7.1
  ====
]

artifact Impfmodule as "vaccination-module-backend.jar" {
  artifact Husky [
    husky-communication-ch.jar
    husky-xua-ch-impl.jar
    2.0.0
    ====
    husky-xua-ch-impl.jar
    ....
    husky-common-gen.jar
    ....
    husky-common-ch.jar
    ....
    husky-fhir-structures-gen.jar
    ....
    husky-xua-gen-api.jar
    ....
    husky-xua-gen-impl.jar
  ]

  artifact fhir_adapter [
    ch.admin.bag.fhir-adapter.jar
    SNAPSHOT 1.0.0
    ====
  ]

  artifact opensaml[
    org.opensaml
    ====
    opensaml-core
  ] 

}

SpringbootParent <-r- Impfmodule

@enduml

